spring:
    application:
        name: el-aparato
    datasource:
        url: jdbc:mysql://localhost:3306/elaparato?serverTimezone=UTC
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/el-aparato-nacholima
        sql:
            init:
                mode: always
server:
    port: 8081

elaparato:
    keycloak:
        serverUrl: http://localhost:8080
        realm: el-aparato-nacholima
        clientId: api-el-aparato-users-client
        clientSecret: 5eZIXbvcFfYs30XDnJK5k6sThMOVqgDU